portfolio/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views as view


app_name = "main"
urlpatterns = [
    path('about/', view.about, name='about'),
    path('', view.index, name='home'),
    path('<str:page>/', view.other_page, name='member'),
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

portfolio/main/models.py
from django.db import models

# Create your models here.

portfolio/main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from django.http import Http404
from django.template import TemplateDoesNotExist


# Create your views here.
def about(request):
    return render(request, 'main/about.html')

def index(request):
    return render(request, 'main/index.html')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))
    

portfolio/main/templates/layout/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная{% endblock %} - Сайт портфолио команды Imagination Engine</title>

    {% block head %}{% endblock %}
</head>
<body>
    "Это с базовой страницы"
    <a href="{% url 'main:home' %}">Главная страница</a>
    {% block content %}{% endblock %}
    
    <a href="{% url 'main:member' page='gazik' %}">Страница Газика</a><br>
    <a href="{% url 'main:member' page='emil' %}">Страница Эмиля</a><br>
    <a href="{% url 'main:member' page='ilya' %}">Страница Ильи</a><br>
    <a href="{% url 'main:member' page='vlad' %}">Страница Влада</a><br>
    <a href="{% url 'main:about' %}">О нас</a>
    <span>test-gazik</span>
</body>
</html>

portfolio/main/templates/main/about.html
{% extends "layout/base.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
<h1>Привет мир! Мы замутили новый проект!</h1>
<h1>☕</h1>
{% endblock %}

portfolio/main/templates/main/emil.html
{% extends "layout/base.html" %}

{% block title %}Участник проекта - Эмиль{% endblock %}

{% block content %}
<h1>Привет, я Эмиль! Это моё портфолио!</h1>
<h1>☕</h1>
{% endblock %}

portfolio/main/templates/main/gazik.html
{% extends "layout/base.html" %}

{% block title %}Участник проекта - Газик{% endblock %}

{% block content %}
<h1>Привет, я Газик! Это моё портфолио!</h1>
<h1>☕</h1>
{% endblock %}

portfolio/main/templates/main/ilya.html
{% extends "layout/base.html" %}

{% block title %}Участник проекта - Илья{% endblock %}

{% block content %}
<h1>Привет, я Илья! Это моё портфолио!</h1>
<h1>☕</h1>
{% endblock %}

portfolio/main/templates/main/index.html
{% extends "layout/base.html" %}

{% block title %}Главная сайта{% endblock %}

{% block content %}
<h1>Привет мир! Это Главная сайта</h1>
<h1>☕</h1>
{% endblock %}

portfolio/main/templates/main/vlad.html
{% extends "layout/base.html" %}

{% block title %}Участник проекта - Влад{% endblock %}

{% block content %}
<h1>Привет, я Влад! Это моё портфолио!</h1>
<h1>☕</h1>
{% endblock %}